Move charts to templates
PayFit/charts pull request #10
Opened 2020-12-07 12:03 UTC by lucchmielowski

# Description

Attempts at moving to monolithic chart from subcharts to make our life easier for now

2020-12-07 12:06 UTC, eddycharly approved these changes

2020-12-07 12:26 UTC, Atrax1 requested changes
Why not creating folder charts in nsq that contains nsqd, nsqlookupd and nsqadmin ?
It is not the way to put everything in templates.. Maybe I'm missing some reasons

2020-12-08 10:26 UTC, lucchmielowski commented
@Atrax1 Well, we tried putting everything in `/charts` but decided to move from that to a monolith for now as it's a real pain in the ass to maintain, for example when working with local `dependencies` and `_helpers` files. If we wanted to have a nsq _umbrella chart_ the real way to do it would be to have something like : 
```
├── charts
│   ├── nsq
│   │   ├── Chart.yaml # umbrella chart requiring the 3 other charts
│   │   └── values.yaml
│   ├── nsqd
│   │   ├── Chart.yaml
│   │   └── values.yaml
│   ├── nsqadmin
│   │   ├── Chart.yaml
│   │   └── values.yaml
│   ├── nsqlookupd
│   │   ├── Chart.yaml
│   │   └── values.yaml
```

2020-12-08 10:51 UTC, RiceBowlJr commented on charts/nsq/templates/nsqadmin/tests/test-connection.yaml
> +<<<<<<< HEAD:charts/nsq/charts/nsqadmin/templates/tests/test-connection.yaml
Oupsy

2020-12-08 11:35 UTC, Atrax1 commented
> @Atrax1 Well, we tried putting everything in `/charts` but decided to move from that to a monolith for now as it's a real pain in the ass to maintain, for example when working with local `dependencies` and `_helpers` files. If we wanted to have a nsq _umbrella chart_ the real way to do it would be to have something like :
> 
> ```
> ├── charts
> │   ├── nsq
> │   │   ├── Chart.yaml # umbrella chart requiring the 3 other charts
> │   │   └── values.yaml
> │   ├── nsqd
> │   │   ├── Chart.yaml
> │   │   └── values.yaml
> │   ├── nsqadmin
> │   │   ├── Chart.yaml
> │   │   └── values.yaml
> │   ├── nsqlookupd
> │   │   ├── Chart.yaml
> │   │   └── values.yaml
> ```
> 
> Since we do not want to separate those 3 entities ATM, we chose to put everything under the same chart for now and move it later if we need.

I was not seing it like that either you don't require in nsq the 3 other chart but it would rather be nsq is parent chart containing charts folder with those 3 charts

2020-12-08 12:41 UTC, lucchmielowski commented on charts/nsq/templates/nsqadmin/tests/test-connection.yaml
> +<<<<<<< HEAD:charts/nsq/charts/nsqadmin/templates/tests/test-connection.yaml
Oh common git !

2020-12-08 12:46 UTC, lucchmielowski commented
@Atrax1 From what I understand, what you mean is something that looks like : 

```
├── charts
│   ├── nsq
│   │   ├── charts
│   │   │   ├── nsqd
│   │   │   ├── nsqadmin
│   │   │   ├── nsqlookupd
│   │   └── values.yaml
```

but if you look at the PR, that's what we're trying to move from as using subchart like that forces us to create hack on the charts configuration (for example putting empty `repository` in dependencies, etc) to make stuff work (although the Helm doc says it's possible)

2020-12-08 12:49 UTC, Atrax1 commented
> @Atrax1 From what I understand, what you mean is something that looks like :
> 
> ```
> ├── charts
> │   ├── nsq
> │   │   ├── charts
> │   │   │   ├── nsqd
> │   │   │   ├── nsqadmin
> │   │   │   ├── nsqlookupd
> │   │   └── values.yaml
> ```
> 
> but if you look at the PR, that's what we're trying to move from as using subchart like that forces us to create hack on the charts configuration (for example putting empty `repository` in dependencies, etc) to make stuff work (although the Helm doc says it's possible)

Yes like this but I don't get it why we are talking about dependencies and hacks here. It is the proper way to do it

2020-12-08 14:21 UTC, RiceBowlJr commented on charts/nsq/templates/nsqadmin/tests/test-connection.yaml
> +<<<<<<< HEAD:charts/nsq/charts/nsqadmin/templates/tests/test-connection.yaml
J'ai fix.

2020-12-09 11:20 UTC, RiceBowlJr approved these changes
OK for me. Agree on the principle (did struggle with you and did not find a chart done with subcharts in charts in any upstream charts 🤔).

2020-12-10 17:02 UTC, closed without merging